PKGNAME := cbuild
LIBBUILD_HEADERS := $(PKGINC_H) $(CPARSE_HEADERS)
LIBBUILD_INCLUDES := $(PKGINCDIR) $(CPARSE_INCLUDES)
LIBBUILD_DRIVERS := $(PKGDRV_OBJ)

LIBBUILD_SRC := $(PKGSRCDIR)
LIBBUILD_H := $(PKGSRC_H)
LIBBUILD_INTDIR := $(INTSRCDIR)
LIBBUILD_OBJ := $(PKGSRC_OBJ)
LIBBUILD_GCDA := $(PKGSRC_GCDA) $(PKGDRV_GCDA)
LIBBUILD_DRV := $(PKGDRVDIR)
LIBBUILD_DRVDIR := $(INTDRVDIR)
LIBBUILD := $(PKGLIB)

.PHONY: cbuild
cbuild: $(LIBBUILD)

$(LIBBUILD): $(LIBBUILD_OBJ)
	@mkdir -p $(@D)
	ar rcs $@ $(LIBBUILD_OBJ)

$(LIBBUILD_INTDIR)%.o: $(LIBBUILD_SRC)%.c $(LIBBUILD_H) $(LIBBUILD_HEADERS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(LIBBUILD_SRC) $(LIBBUILD_INCLUDES)) $(CFLAGS) -o $@ $<

$(LIBBUILD_DRVDIR)%.o: $(LIBBUILD_DRV)%.c $(LIBBUILD_H) $(LIBBUILD_HEADERS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(LIBBUILD_DRV) $(LIBBUILD_INCLUDES)) $(CFLAGS) -o $@ $<

LIBBUILD_TEST_LIBS := $(LIBBUILD) $(CPARSE) $(CUTILS) $(CTEST) $(CBASE)

LIBBUILD_TEST_SRC := $(PKGTESTDIR)
LIBBUILD_TEST_H := $(PKGTEST_H)
LIBBUILD_TEST_INTDIR := $(INTTESTDIR)
LIBBUILD_TEST_OBJ := $(PKGTEST_OBJ)
LIBBUILD_TEST_GCDA := $(PKGTEST_GCDA)
LIBBUILD_TEST := $(PKGTEST)

.PHONY: cbuild/test
cbuild/test: $(LIBBUILD_TEST)
	@rm -rf $(LIBBUILD_GCDA) $(LIBBUILD_TEST_GCDA)
	$(LIBBUILD_TEST)

$(LIBBUILD_TEST): $(LIBBUILD_DRIVERS) $(LIBBUILD_TEST_OBJ) $(LIBBUILD_TEST_LIBS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) $(LDFLAGS) -o $@ $(LIBBUILD_TEST_OBJ) $(LIBBUILD_DRIVERS) -L$(BUILDDIR)bin/$(ARCH)-$(CONFIG)/libs $(patsubst %,-l:%,$(notdir $(LIBBUILD_TEST_LIBS)))

$(LIBBUILD_TEST_INTDIR)%.o: $(LIBBUILD_TEST_SRC)%.c $(LIBBUILD_TEST_H)$(LIBBUILD_HEADERS) $(CTEST_HEADERS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(LIBBUILD_TEST_SRC) $(LIBBUILD_INCLUDES) $(CTEST_INCLUDES)) $(CFLAGS) -o $@ $<
