name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  workflow_dispatch:

jobs:
  bootstrap-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib lcov -y

      - name: Bootstrap
        run: ./scripts/bootstrap.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap-linux
          path: bin

  bootstrap-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap
        run: ./scripts/bootstrap.bat

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap-windows
          path: bin

  build-linux:
    needs: bootstrap-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gen: [M, C]
        arch: [host, x64, x86]
        conf: [Debug, Release]
        include:
          - targets: all test
          - arch: host
            conf: Debug
            targets: cov

    steps:
      - uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v5
        with:
          name: bootstrap-linux

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib lcov -y

      - name: Build
        run: ./scripts/build.sh -g ${{matrix.gen}} -a ${{ matrix.arch }} -c ${{ matrix.conf }} -t "${{ matrix.targets }}" -O 0

      - name: Coverage
        if: matrix.gen == 'M' && matrix.arch == 'host' && matrix.conf == 'Debug'
        uses: coverallsapp/github-action@v2

      - name: Upload
        if: matrix.gen == 'M' && matrix.arch != 'host'
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-${{ matrix.arch }}-${{ matrix.conf }}
          path: bin/${{ matrix.arch }}-${{ matrix.conf }}/bin

  build-windows:
    needs: bootstrap-windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [host, x64, x86]
        conf: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v5
        with:
          name: bootstrap-windows

      - name: Build
        run: ./scripts/build.bat -a ${{ matrix.arch }} -c ${{ matrix.conf }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-${{ matrix.arch }}-${{ matrix.conf }}
          path: bin/${{ matrix.arch }}-${{ matrix.conf }}/bin

  test-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, x86]
        conf: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v5
        with:
          name: build-linux-${{ matrix.arch }}-${{ matrix.conf }}

      - name: Test
        run: ./scripts/test.sh ${{ matrix.arch }} ${{ matrix.conf }}

  test-windows:
    needs: build-windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
        conf: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v5
        with:
          name: build-windows-${{ matrix.arch }}-${{ matrix.conf }}

      - name: Test
        run: ./scripts/test.bat ${{ matrix.arch }} ${{ matrix.conf }}

  release:
    needs: [test-linux, test-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Save Release URL
        run: echo "release_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT

  upload:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plat: [linux, windows]
        arch: [x64, x86]

    steps:
      - name: Download
        uses: actions/download-artifact@v5
        with:
          name: build-${{ matrix.plat }}-${{ matrix.arch }}-Release
          path: ${{ matrix.plat }}-${{ matrix.arch }}

      - name: Upload
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ matrix.plat }}-${{ matrix.arch }}/build
          asset_name: build- ${{ matrix.plat }}-${{ matrix.arch }}
          asset_content_type: application/binary
