name: ITest

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  workflow_dispatch:

jobs:
  Ubuntu-Make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, x86]
        conf: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib lcov -y

      - name: Test
        run: ./scripts/test.sh ${{ matrix.arch }} ${{ matrix.conf }}

  Windows-CMake:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
        conf: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: ./scripts/test.bat ${{ matrix.arch }} ${{ matrix.conf }}
