name: ITest

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  workflow_dispatch:

jobs:
  Ubuntu-Make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conf: [Debug, Release]
        arch: [x64, x86]

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib -y

      - name: Test
        run: ./scripts/test.sh ${{ matrix.arch }} ${{ matrix.conf }}
